### ISSUE TITLE
Python 3 Support?

### ISSUE THREAD

**Issue by wldcordeiro** [bee-keeper/django-invitations#1]
According to Django Packages this doesn't support Python 3. Is this true or not? If it is, I'm willing to make a PR updating it to support Python 3.

**Comment by bee-keeper** [comment]
@wldcordeiro - I think it may well be python 3 compatible but can't be sure as I have not tested it.  Would really appreciate a pull request or even just let me know how you get on.

**Comment by wldcordeiro** [comment]
@bee-keeper I'm going to try it and see. It looks like it supports Python 3 from looking at the code base and just setting up the basic config.

**Comment by bee-keeper** [comment]
Hi there,

Am closing this as I have set up a testing suite with travisCI in the devel branch.  I'm aiming for complete compatibility with Django 1.5-1.8 and Python 2.6, 2.7, 3.2, 3.3 and 3.4.  I'll then merge this into master and release a new package.
