### ISSUE TITLE
NoReverseMatch Error in Django 2.0

### ISSUE THREAD

**Issue by Jromero97** [bee-keeper/django-invitations#101]
Hi, I have an error using your package with django 2.0, it's unable to found the pattern for views! and throw me a NoReverseMatch error, that could be 'cause the URL format? or something similar?

**Comment by bee-keeper** [comment]
Hi,
You'll see in test matrix we're testing against Django 2.0 so I'm fairly sure that's not the issue.  Could you post the exact error and also versions of invitations and allauth?

Thanks,

**Comment by Jromero97** [comment]
Any possibility of I don't have to use django-allauth for authentication?

**Comment by bee-keeper** [comment]
You don't have to use it no.  But django-allauth works with Django 2.0 so if you upgrade to latest version that may resolve your issue?

**Comment by Jromero97** [comment]
![image](https://user-images.githubusercontent.com/27448401/36615329-6a480636-18a5-11e8-9f8f-54be805ac849.png)

This is the error when I try to activate from email!

**Comment by bee-keeper** [comment]
As I said, please post versions of invitations and allauth you're using.  Also please post the code you use to add invitation urls to your project.

**Comment by Jromero97** [comment]
I'm using version 1.9.2 of django-invitations and not using django-allauth...
![image](https://user-images.githubusercontent.com/27448401/36632314-f8ad4a6c-194a-11e8-97fe-bbbc3d16fd30.png)
That's the url configuration in my project!

**Comment by bee-keeper** [comment]
Try as per the test settings at the link I posted above.

**Comment by Jromero97** [comment]
I already tried with that settings

**Comment by Jromero97** [comment]
I realized that the problem is when it tries to redirect to signup view but i don't have django-allauth. So, how is the best way to customize those views, with my own views?

**Comment by bee-keeper** [comment]
That's entirely up to you and the way you choose to handle registration/authentication.
