### ISSUE TITLE
Inviter as logged user

### ISSUE THREAD

**Issue by Jromero97** [bee-keeper/django-invitations#102]
Hello again! this time, I wanna that invitations set the inviter automatically as request.user, how can I do this, without show 'inviter' field in django admin.?

**Comment by JeansReal** [comment]
@Jromero97 

Override the save form

    def save_form(self, request, form, change):
        """ Override the save form, to create the invitation and add the inviter_id for the logged user. """
        obj = super(CustomInvitationAdmin, self).save_form(request, form, change)
        obj.inviter = request.user  # Default user that create the invitation is the logged user.
        return obj
