### ISSUE TITLE
Question about GPL License

### ISSUE THREAD

**Issue by amitjindal** [bee-keeper/django-invitations#115]
Hi,

I wanted to know if this module can be used in a commercial application. GPL licensing is tricky and we try to avoid it for commercial use. I wish this was MIT or BSD licensed.

In this case we are installing this as a library dependency. However since it is being used (imported) in the code, does that means by using this we will be violating GPL?

Requesting @bee-keeper to please help clarify. If anyone else can provide feedback will appreciate that as well.

Thanks
Amit

**Comment by FredeJ** [comment]
As a general rule of thumb, GPL means that if you distribute your code to anyone, in any form including binary, you must give them access to the source code as well.

If you are simply running a webserver using modules with a GPL license, you are not distributing your code - you are simply running the code and other people are interacting with it - and therefore you have no obligation to turn over your code to anyone.

I am not a lawyer, but this is my understanding.

**Comment by amitjindal** [comment]
@FredeJ Thank you for your explanation. Will consider this.

**Comment by speightashley** [comment]
I had the same query. GPL licence makes it very difficult if a project gets acquired. VC's often ask for licence types of dependencies.

Is there any considerations on making this MIT or BSD licenced?

If not, it would be better for me to write something similar from scratch. :-(
