### ISSUE TITLE
Admin invitations

### ISSUE THREAD

**Issue by nwaxiomatic** [bee-keeper/django-invitations#14]
I modified the admin for the invitations to be able to send the email invitations directly from the admin, would this be an addition of interest?

**Comment by bee-keeper** [comment]
Hi there, yes potentially but it depends on how it is done.  Essentially, to invite someone you would just need to add an invitation in admin by filling in their email and then kicking off the invite process on the form save.  It should be possible to do this without custom admin hacks and I think it would be very useful indeed.

Please feel free to PR request an implementation.

**Comment by bee-keeper** [comment]
Closed as now [implemented](https://github.com/bee-keeper/django-invitations/commit/3fd22ed2f320e461aec6e19e4bc3cfe35818dd3b)
