### ISSUE TITLE
Transfer project ownership to Jazzband?

### ISSUE THREAD

**Issue by brylie** [bee-keeper/django-invitations#165]
The [Jazzband organization](https://jazzband.co/) actively maintains several [Django projects](https://jazzband.co/projects), many of which are in wide use. Jazzband has tools and a process in place for project governance, to encourage sustainability of projects.

Would you consider transferring the ownership of this project to the Jazzband organization in order to encourage the sustained development of django-invitations?

**Comment by pbadeer** [comment]
@brylie @bee-keeper I love this idea. The community is rallying around this project, there are over a dozen pull requests ready for review. For me, if this doesn't show signs of life soon then I have to find something actively maintained to avoid putting my clients at risk.

**Comment by bee-keeper** [comment]
Hi, I'd be more than happy to do that.  Sorry I just don't have time to give this project the support it needs.

**Comment by brylie** [comment]
Thanks @bee-keeper 😃 

I'll open a discussion in the JazzBand community.

**Comment by brylie** [comment]
The initial response was to make sure the django-invitations project is following the [JazzBand project guidelines](https://jazzband.co/about/guidelines).

**Comment by brylie** [comment]
I have opened a pull request (#166) with changes related to the [JazzBand project guidelines](https://jazzband.co/about/guidelines). @pbadeer and @bee-keeper, would you mind reviewing the JazzBand guidelines and my pull request to ensure we are conformant?

**Comment by brylie** [comment]
I opened a [proposal](https://github.com/jazzband/help/issues/237) to transfer ownership of django-invitations to the JazzBand community.

**Comment by shawnngtq** [comment]
follow
