### ISSUE TITLE
inviter id included in invitations table

### ISSUE THREAD

**Issue by sitrucp** [bee-keeper/django-invitations#17]
What would it take to save the inviter id in invitations_invitation table? I want to associate them together as a team. Thx!

**Comment by bee-keeper** [comment]
There's currently a signal which returns you the inviter.

You could use that and then create your own table which maps the invite and the inviting user.  

That said, it seems this is a common request though so I would accept a PR which adds the inviter on the invitation model.

**Comment by sitrucp** [comment]
I added inviter to Invitation model and then update it with request.user.id when invite is sent.  For now it is just integer not foreign key.

After the accepted invitation is sent to allauth signup form, I can get inviter user id and update my user record with that user's team id.

**Comment by bee-keeper** [comment]
ok cool.
