### ISSUE TITLE
Invite link url trailing slash not included in link - Android email

### ISSUE THREAD

**Issue by sitrucp** [bee-keeper/django-invitations#18]
While the invite email link url's trailing slash is in the invite email, it is not included in the active link in my Android's email message so it gives 404 not found. This is a rare case but if trailing slash was not present then it wouldn't ever be an issue.

The url is built in model.py:
invite_url = request.build_absolute_uri(invite_url)

Not sure where trailing slash is being added. Does build_absolute_uri add it ? Documentation indicates it doesn't?

[https://docs.djangoproject.com/en/1.8/ref/request-response/#django.http.HttpRequest.build_absolute_uri](https://docs.djangoproject.com/en/1.8/ref/request-response/#django.http.HttpRequest.build_absolute_uri)

**Comment by bee-keeper** [comment]
A temporary solution might be removing the trialing slash in the urls [conf](https://github.com/bee-keeper/django-invitations/blob/master/invitations/urls.py).

**Comment by bee-keeper** [comment]
Hi, I'm closing this issue, this [merge](https://github.com/bee-keeper/django-invitations/pull/19) makes the slash optional.

Thanks for reporting,
