### ISSUE TITLE
Unable to use different adapter when using allauth

### ISSUE THREAD

**Issue by clokep** [bee-keeper/django-invitations#28]
It seems that the code around `get_invitations_adapter` breaks if `ACCOUNT_ADAPTER` is set, but is *NOT* equivalent to `'invitations.models.InvitationsAdapter'`. In this case `get_invitations_adapter` returns `None`.

My use case is that I'm using allauth with [allauth_2fa](https://github.com/percipient/django-allauth-2fa/), which overrides the `ACCOUNT_ADAPTER`.

~~(Also, as an aside, I think the implementation of [`is_open_for_signup` of `InvitationsAdapter`](https://github.com/bee-keeper/django-invitations/blob/f95e9a16684235f0c614e0371d0f3bb5ca41d470/invitations/models.py#L88-L97) is equivalent to the [`DefaultAccountAdapter` implementation](https://github.com/bee-keeper/django-invitations/blob/ef87e69c96d800c9c68d739db6de8f8316e4e929/invitations/adapters.py#L73-L82).)~~ They're inheriting from different models, never mind. :+1:

**Comment by clokep** [comment]
What I had tried was:

```python
# DJANGO ALL-AUTH CONFIGURATION
# See http://django-allauth.readthedocs.org/en/latest/configuration.html
# ...
ACCOUNT_ADAPTER = "allauth_2fa.adapter.OTPAdapter"
# END DJANGO ALL-AUTH CONFIGURATION

# DJANGO INVITATIONS CONFIGURATION
# See https://github.com/bee-keeper/django-invitations#additional-configuration
INVITATIONS_ADAPTER = ACCOUNT_ADAPTER
# END DJANGO INVITATIONS CONFIGURATION
```

The workaround I have is:
```python
# DJANGO ALL-AUTH CONFIGURATION
# See http://django-allauth.readthedocs.org/en/latest/configuration.html
# ...
ACCOUNT_ADAPTER = "allauth_2fa.adapter.OTPAdapter"
# END DJANGO ALL-AUTH CONFIGURATION


# DJANGO INVITATIONS CONFIGURATION
# See https://github.com/bee-keeper/django-invitations#additional-configuration
INVITATIONS_ADAPTER = ACCOUNT_ADAPTER
# Since the above is actually broken...
from allauth.account.adapter import get_adapter
from invitations import adapters

adapters.get_invitations_adapter = get_adapter
# END DJANGO INVITATIONS CONFIGURATION
```

**Comment by bee-keeper** [comment]
All good then - can I close?

**Comment by clokep** [comment]
As long as this is not a supported use case, feel free to close yep! :)

**Comment by clokep** [comment]
Although, I think the fix is as easy as combining the [two boolean statements here](https://github.com/bee-keeper/django-invitations/blob/f95e9a16684235f0c614e0371d0f3bb5ca41d470/invitations/adapters.py#L111-L112) into a single statement with `and`.

**Comment by bee-keeper** [comment]
Ok please do - if it passes the tests I'll give it a proper look over and get it merged.

Thanks,
