### ISSUE TITLE
inviter not set when using SendInvite view

### ISSUE THREAD

**Issue by clokep** [bee-keeper/django-invitations#29]
I would expected the `inviter` field of an `Invitation` to be set when using the `SendInvite` view since it requires a logged in user.

I think this just needs an extra line before [sending the invite](https://github.com/bee-keeper/django-invitations/blob/ef87e69c96d800c9c68d739db6de8f8316e4e929/invitations/views.py#L30) that sets:
```python
invite.inviter = request.user
invite.save()
```

I'm willing to make a PR for this, if you can confirm this is the expected behavior. :smile:

**Comment by bee-keeper** [comment]
Hi,

Hmm, looks like you're right, please submit a PR to devel and I'll get this merged ASAP.

Thanks!!
