### ISSUE TITLE
Site set to invite only

### ISSUE THREAD

**Issue by brandonjschwartz** [bee-keeper/django-invitations#36]
Maybe I'm doing this wrong...

I have settings as:

`INVITATIONS_INVITATION_EXPIRY = 14
INVITATIONS_INVITATION_ONLY = True
INVITATIONS_GONE_ON_ACCEPT_ERROR = False
INVITATIONS_SIGNUP_REDIRECT = '/u/register/'
INVITATIONS_CONFIRM_INVITE_ON_GET = True
INVITATIONS_ALLOW_JSON_INVITES = False
INVITATIONS_LOGIN_REDIRECT = LOGIN_URL`

I can invite users just fine, but I can also register directly at the signup page. Is there something I need to change to the signup view?

**Comment by bee-keeper** [comment]
Hi, you need to set the ACCOUNT_ADAPTER as specified in the readme.

**Comment by brandonjschwartz** [comment]
Thanks. I configured the setting and installed allauth; everything worked fine after that :)

**Comment by Slyyxp** [comment]
I'm having this same issue, but with the exception I have ACCOUNT_ADAPTER set and allauth installed.
/register/ is still accessible with `INVITATIONS_INVITATION_ONLY = True` set.

Maybe I have missed something.

```
# settings.py

INSTALLED_APPS = [
    'django.contrib.auth',
    'django.contrib.messages',
    'django.contrib.sites',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'django.contrib.admin',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.staticfiles',
    'main.apps.MainConfig',
    'register',
    'channels',
    'invitations',
    'tests',
]

# Invitation settings
INVITATIONS_INVITATION_EXPIRY = 14 
INVITATIONS_INVITATION_ONLY = True
INVITATIONS_ACCEPT_INVITE_AFTER_SIGNUP = False
INVITATIONS_GONE_ON_ACCEPT_ERROR = False 
INVITATIONS_SIGNUP_REDIRECT = '/register/' 
INVITATIONS_CONFIRM_INVITE_ON_GET = True 
INVITATIONS_ALLOW_JSON_INVITES = False 
INVITATIONS_LOGIN_REDIRECT = '/login/'
ACCOUNT_ADAPTER = 'invitations.models.InvitationsAdapter'
```

```
# simple register view
def register(request):
    form = CreateUserForm()
    if request.method == 'POST':
        form = CreateUserForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('login')

    context = {'form':form}
    return render(request, 'register/register.html', context)
```
