### ISSUE TITLE
Lack of documentation

### ISSUE THREAD

**Issue by rcastill** [bee-keeper/django-invitations#37]
Hey there! I am using your app, for a college project, and I am encountering issues at understanding the complete flow of the app because of the lack of documentation.

I applied the steps suggested in README.md (not using allauth) and "it works". But I cannot figure out how to make my site invite only, that is, I want SIGNUP_REDIRECT to be accesible only by clicking on an invitation link, I thought that was your INVITATION_ONLY config meant to, but it does not seem to do any logical change, I tried inspecting the source but didn't get too further.

So, I am here for advice, does your app support this??

Another thing, but it does not have to do with your app; from time to time, sending invitations crashes in SSLEOFError (or something like that) saying that there has been a protocol violation. I tested sending standalone mails, and that error also happened to raise some of the times.

That's it, I hope you can help me.
Regards!

**Comment by bee-keeper** [comment]
Hi there,

The setting you're referring to only makes sense when using allauth for authentication.  If you're not using allauth then it's your responsibility to work this feature into your authentication implementation.  It's true this needs adding to the docs and I'll leave this open until that's done.

**Comment by rcastill** [comment]
Thanks! I'll take a look into allauth
