### ISSUE TITLE
Email is not sent.

### ISSUE THREAD

**Issue by brunoliveira8** [bee-keeper/django-invitations#38]
Hello,

For some reason, the email is not sent. I have tried on my local machine and on Pythonanywhere, I have configured as shown on the readme.md

Thanks!

**Comment by bee-keeper** [comment]
Hello, 

This is surely a problem with your email settings.  Try using the console [backend](https://docs.djangoproject.com/ja/1.9/topics/email/#console-backend) to verify the mail is sent.

**Comment by brunoliveira8** [comment]
Thanks, I tried the backend but I made a mistake. Now is working.
