### ISSUE TITLE
Remove unique constraint on email

### ISSUE THREAD

**Issue by gnublade** [bee-keeper/django-invitations#43]
Would you consider removing the constraint on emails being unique?

I was considering submitting a PR to make it optional with a setting in app_settings, but it seems like it may be a common use-case to be able to send multiple invites - such as after an initial invite has expired.

With the current constraint, the original invitation must be deleted first. A user following a previously expired invitation would then receive an error instead of a message that the invitation had expired.

If email isn't unique we can keep track of who sent invitations and when.

Many thanks for this app - simple but effective!

**Comment by bee-keeper** [comment]
Hi there,

I'm surprised this hasn't come up before actually.  Your point about sending another invite after one has expired needs to be addressed but I'm not sure app_settings is the way to go about this as it would require migrations.

Thinking aloud, perhaps invites can be unique on email only if they have either not been accepted or have not yet expired.  I'm fairly sure this wouldn't affect anything else but I would have to check to make sure.

Thanks for bringing this up, and if you see a solution that works please feel free to PR!

**Comment by nsomaru** [comment]
Well, looking at the use case this package addresses, if an invitation has expired it is because project requirements dictate as much; if an invitation has expired it probably means the invited user has forgotten about or ignored your invitation. Conclusion: you need to remind them.

Since you need to remind them anyways, add an admin action which calls `Invitation.send()`, which will update `Invitation.sent` and give you the convenient side-effect of reminding the user too :smirk: 

Alternatively, if @bee-keeper thinks we need a specific remind template we could implement `Invitation.remind()` or expand the signature of `Invitation.send()` to accept an optional template.

**Comment by fmarco** [comment]
@bee-keeper @nsomaru  Any update on this one? :)
It would be useful to setup the unique attribute on the field, or extend in some way the model / behaviour to decide how to group invitations. In some cases email uniqueness is too restrictive.
At the moment i'm thinking about two way:

1) setup the unique in the project settings
2) create a base model for invitations a let decide the user if using the default current invitation model (that will inherit from the new base model) or extend the base model to add behaviour and new fields.

I'm interested in making a PR, eventually :).

**Comment by bee-keeper** [comment]
Certainly in terms of my priorities, I want to make the invitation model swappable (much like User model in Django).  Adding remind functionality to that would come second.  If you want to make a start on a swappable invitations model feel free!

**Comment by fmarco** [comment]
@bee-keeper just opened a PR, what do you think?

**Comment by bee-keeper** [comment]
Closing this as it can be solved by using the swappable invite model.

**Comment by daino3** [comment]
Hello. I've tried adding `class Invitation(AbstractBaseInvitation):` to remove uniqueness on the email field, however, django still sources your migrations. Is there a flag to ignore `invitations` migrations and rely on my custom implementation's generated migration? I can add to the README with instructions if someone helps me figure this out. 

Thanks!

**Comment by clokep** [comment]
@daino3 Are you including `invitations` in your installed apps setting? You'll need to remove that to use custom models.

**Comment by daino3** [comment]
@clopek I am. If I remove it I get:

```
  File "/vagrant/common/models/__init__.py", line 11, in <module>
    from .invitation import Invitation
  File "/vagrant/common/models/invitation.py", line 16, in <module>
    from invitations.models import AbstractBaseInvitation
  File "/home/vagrant/venvs/salons/lib/python3.5/site-packages/invitations/models.py", line 22, in <module>
    class Invitation(AbstractBaseInvitation):
  File "/home/vagrant/venvs/salons/lib/python3.5/site-packages/django/db/models/base.py", line 108, in __new__
    "INSTALLED_APPS." % (module, name)
RuntimeError: Model class invitations.models.Invitation doesn't declare an explicit app_label and isn't in an application in INSTALLED_APPS.
```

**Comment by clokep** [comment]
@daino3 You'll want to import your subclass of `Invitation`.

**Comment by scambrayj** [comment]
can anyone provide a code example on how to remove the unique constraint on email?  It seems by the solution posted here, using the 'swappable' model is the way to go.  Can someone point me in the right direction as how to accomplish this?
