### ISSUE TITLE
Needing help on how to implement the invitations with my event platform

### ISSUE THREAD

**Issue by luanfonceca** [bee-keeper/django-invitations#48]
Hi folks, i am using the allauth for login and signup and now i need to Invite people to my events.
I am thinking on how to do that, i have the following scheme: Event with 1:n relation with Attendee, as the event organizer i would like to invite other users to my event.

![invitations-process](https://cloud.githubusercontent.com/assets/1490875/18889606/0f8c2c88-84d4-11e6-935b-8814aecb088e.png)

In my mind this a nice and simple worflow for this process, i dont want just the receiver of the invitation to become a user in my plataform but i need it to become a attendee of the event that he/she was invited.

In the coding i have a page for the organizer to send invites to emails. The users confirm they invitations and i would like to add that users to the organizer's event. I think on after the users login/sign up (in the `populate_user` method inside a `CustomSocialAccountAdapter` allauth adapter) i will look in the `Invitation` models for email of that user and if i found some invite i add that user to that event.

```py
# attendee/custom_adapter.py

class CustomSocialAccountAdapter(DefaultSocialAccountAdapter):
    def populate_user(self, request, sociallogin, data):
        email = sociallogin.account.extra_data.get('email')
        user = User.objects.get(email=email)

        try:
            invite = Invitation.objects.get(email=email)
        except Invitation.DoesNotExist:
            pass
        else:
            if not invite.activity.attendees.filter(user=user).exists():
                Attendee.objects.create(
                    activity=activity,
                    profile=user.profile
                )

```

I tried to make this on the siganls but it is never called:

```py
# attendee/models.py

from django.dispatch import receiver
from django.contrib.auth.models import AnonymousUser

from invitations.signals import invite_accepted

@receiver(invite_accepted, sender=AnonymousUser)
def invite_accepted(sender, request, email, **kwargs):
    ...
```

Can you folks help me telling me if there is a easiest way of doing this?

Thanks in advance.

**Comment by bee-keeper** [comment]
Sorry for the delay, I suppose you might be best using the basic adapter and then creating the bespoke functionality yourself.  That's basically what it's for - it gives you the invite skeleton but you'll need to fill in the rest of the details.

**Comment by DanielTea** [comment]
Sorry for reopening this old issue.

I have the same trouble right now, could you point out some examples and tutorial links?
