### ISSUE TITLE
How to pass custom data to invite email

### ISSUE THREAD

**Issue by thewebsitedev** [bee-keeper/django-invitations#50]
Hello,

Thank you for the good work.

How can I pass in custom data to the invite email?

**Comment by bee-keeper** [comment]
This happens [here](https://github.com/bee-keeper/django-invitations/blob/master/invitations/models.py#L55).

**Comment by mrHaugen** [comment]
Sorry, I don't get this. Can I pass any custom data along with the invitation, or is it limited to invite_url, site_name, email, key and inviter?

**Comment by bee-keeper** [comment]
Yes, it's currently limited to to those variables.  

It should be modified though so that you can pass in additional kwargs.  In fact, this wuld be a good feature so i'll reopen this issue.

**Comment by bee-keeper** [comment]
Hi @nsomaru,

No there currently isn't a generic way to do this. But you're right, it should be possible to point invitations to a custom model much like how Django custom user models work. I'll leave this open until either I have chance to do it, or if someone else PR's.

**Comment by bee-keeper** [comment]
Am closing as we have an open PR for a swappable invitations model.

**Comment by dimkoug** [comment]
for example

invite.send_invitation(self.request, shop=self.shop)

general way

invite.send_invitation(self.request, **kwargs)

and then inside template you can access your custom kwargs
