### ISSUE TITLE
Email length problem

### ISSUE THREAD

**Issue by fmarco** [bee-keeper/django-invitations#52]
Hello,

i've a problem: how can i set up the email length to  a defined value? I need it for a project and it's a blocking issue.
I suppose this needs a PR to modify the behaviour, right? Exactly as here: https://github.com/pennersr/django-allauth/blob/4a6df009ff98255e03a122eb9ea4a90c5eb2aa35/allauth/account/migrations/0002_email_max_length.py

**Comment by bee-keeper** [comment]
I presume you're using mysql hence the issue?  Sure feel free to put together a pull request.

**Comment by fmarco** [comment]
@bee-keeper Exactly. 
Ok, nice, i'll open a PR asap :+1:

**Comment by fmarco** [comment]
@bee-keeper PR opened here: https://github.com/bee-keeper/django-invitations/pull/53

**Comment by fmarco** [comment]
@bee-keeper Very fast, thanks!
