### ISSUE TITLE
Custom Email Template

### ISSUE THREAD

**Issue by craigosborne** [bee-keeper/django-invitations#54]
Hi,

Is it possible to specify a custom email template for invitations? ideally I want an html template.

keep up the good work.

**Comment by bee-keeper** [comment]
Hi there,

Sure it is.  Just follow the allauth convention for this as it uses the same code.  Simply add the template with the same name as the .txt but a .html extension and it should just work (I believe this is how it works with allauth, just take a look at their docs to verify).

**Comment by craigosborne** [comment]
Hi,

Thanks exactly how it works.

**Comment by jwagstaff** [comment]
Howdy, 

Sorry, but I cant figure out the path to place my custom email template in.  Is it templates/account/email (using the all auth template folder) or templates/invitations/email ?  I've tried both and neither is working for me.

**Comment by cobyrne09** [comment]
`templates/invitations/email/email_invite_message.txt` worked for me. There are a couple of configuration steps to make email templates work in general, if I recall, so any people who come across this might want to look for those, if you are having trouble.
