### ISSUE TITLE
Advice on Customising the `Invitation` Model

### ISSUE THREAD

**Issue by nsomaru** [bee-keeper/django-invitations#55]
Hi @bee-keeper,

Thanks for a great project. We use `django-invitations` in one live project and are looking to integrate it into another now.

Our current project requires that we have some custom fields on the `Invitation` model which will be used to render the email. We basically want a personal salutation.

Is there a generic, reusable way to do this? Trying to avoid forking the package. 

edit: this is related to #50. closing

**Comment by bee-keeper** [comment]
Hi @nsomaru,

No there currently isn't a generic way to do this.  But you're right, it should be possible to point invitations to a custom model much like how Django custom user models work.  I'll leave this open until either I have chance to do it, or if someone else PR's.
