### ISSUE TITLE
Add a reminder email function with an optionally different template

### ISSUE THREAD

**Issue by krsmedlund** [bee-keeper/django-invitations#56]
We want to send out reminders to the people that doesnt use their invites for X amount of days, with a different email template.

**Comment by bee-keeper** [comment]
Hi there.  

This doesn't seem like a generic enough request to feature this in invitation.  Sounds like something you could potentially just trigger from a management command?

**Comment by krsmedlund** [comment]
Hi, yea i've already implemented it and trigger it via management command, the ticket was for if you wanted it in a PR as its a quite common thing to do!
