### ISSUE TITLE
Add Cancelled field on Invitation model

### ISSUE THREAD

**Issue by asackofwheat** [bee-keeper/django-invitations#67]
I'm using django-invitations (thanks btw!) and right now, I have functionality to cancel an invite (which right now deletes the Invitation). It would be nice if the Invitation model had a 'cancelled' boolean field which would allow me to soft-delete Invitations. Let me know what you think!

**Comment by sebastibe** [comment]
This would probably be solved by the swappable invitation model #58 no?

**Comment by bee-keeper** [comment]
Hi,

This does  sound useful, but I agree with @sebastibe - all this can be handled with a swappable model and ideally we want to strive for extendable and minimal.

Thanks for the suggestion regardless!
