### ISSUE TITLE
Tracking the number of invited users

### ISSUE THREAD

**Issue by narnikgamarnikus** [bee-keeper/django-invitations#78]
I need to be able to track how many users have been invited by a particular user.

What are the ways to do this?

We can assume that this is a kind of referral system.

I want to know what user this user was invited to.

Please give a brief recommendation on the implementation of this task.

For example:

user 123, user 124 and user 125 was invited by user 7.

Thanks!

**Comment by clokep** [comment]
You can get the invitations by a particular user by accessing the `invitation_set` property:
```python
user = User.objects.get(username='bob')
invitations = user.invitation_set.all()
# invitations is a QuerySet of Invitation model instances.
```

If you want a list of users who have invited anyone it would be done like:
```python
users_with_invites = User.objects.annotate(invitation_count=Count('invitation')).filter(invitation_count__gt=0)
```
