### ISSUE TITLE
Are there ways to integrate with social networks?

### ISSUE THREAD

**Issue by narnikgamarnikus** [bee-keeper/django-invitations#79]
In addition to the invitation via e-mail, I'm looking for an opportunity to invite through the social network.
One of the options that I'm considering is the repost button, which would have some kind of get parameter. I completely understand how to do this separately from your application, but I want to unify the two solutions, and I'm looking for the shortest way for this.

**Comment by bee-keeper** [comment]
I never really figured out a nice flow for integration with social networks so sorry, can't help here.
