### ISSUE TITLE
Can't find docs

### ISSUE THREAD

**Issue by maxnordlund** [bee-keeper/django-invitations#86]
I could find some sort of online docs, like readthedocs.io, which would be nice. More specifically I need to extend the creation of new invitations which I think I van do using the INVITATIONS_INVITATION_MODEL setting. But it's a bit unclear how this should be done, and how a custom adapter should be used as well.

*TL;DR* It would be nice with readthedocs.io style online documentation.

**Comment by bee-keeper** [comment]
I totally agree.  Feel free to PR ;)

**Comment by maxnordlund** [comment]
Hm, I not sure I can since readthedocs is a site where the _owner_ uploads their docs, right?

I must admit I've never needed to publish docs like this, or even use sphinx for that matter, unfortunately. Was kinda hoping you know how to do this.
