### ISSUE TITLE
Django 2.0 support

### ISSUE THREAD

**Issue by craigosborne** [bee-keeper/django-invitations#96]
Any idea when a django 2.0 supported version will be released?

**Comment by bee-keeper** [comment]
Hi sorry for the delay.  I'll try get a release of the current master (supporting 2.0) out in the next few days.

**Comment by avalanchy** [comment]
@craigosborne I think we can left this open unitl new version lands on pypi.

**Comment by RoryOfByrne** [comment]
Hi @bee-keeper do you think we'll see the release in the next week? I'm doing an alpha test next week and I really want to use this!

**Comment by bee-keeper** [comment]
Hi, I just released this morning.  I've updated the test matrix now to support only 1.11 and 2.0 (ie to be consistent with allauth itself).
