### ISSUE TITLE
Possibility to subclass InvitationsAdapter for Allauth use?

### ISSUE THREAD

**Issue by RoryOfByrne** [bee-keeper/django-invitations#99]
I want to subclass `invitations.models.InvitationsAdapter` to change Allauth's default `ajax_response()` method. However, I noticed that the `InvitationsAdapter` class only exists if `settings.ACCOUNT_ADAPTER == 'invitations.models.InvitationsAdapter'`, see [here](https://github.com/bee-keeper/django-invitations/blob/master/invitations/models.py#L79). 

Is this intended? Can it be changed so that I can subclass it and use `ACCOUNT_ADAPTER = 'path.to.my.subclass'`? Or is there a way to subclass `InvitationsAdapter` that I'm not seeing?

**Comment by clokep** [comment]
I ran into this while using a package we wrote (django-allauth-2fa), I got around it by doing this:

```python
from allauth.account.signals import user_signed_up

from allauth_2fa.adapter import OTPAdapter


class MyAdapter(OTPAdapter):
    """An allauth adapter that includes both 2FA and invitations support."""

    # Ideally we'd just import InvitationsAdapter and inherit from it, but you
    # can't import InvitationsAdapter unless we set ACCOUNT_ADAPTER to be it.
    # Just copy the functionality here.
    def get_user_signed_up_signal(self):
        return user_signed_up
```

**Comment by RoryOfByrne** [comment]
Thanks @clokep. I was planning to just copy the InvitationsAdapter functionality if needed but I was hoping I could avoid it.

Did you not need the `is_open_for_signup(self, request)` functionality or is there another reason why you didn't copy that method?

**Comment by clokep** [comment]
[`OTPAdapter` subclasses `allauth.account.adapter.DefaultAccountAdapter`](https://github.com/percipient/django-allauth-2fa/blob/3df938736c19480a478a01f5f08506d20ef211da/allauth_2fa/adapter.py#L16), which [provides that method](https://github.com/pennersr/django-allauth/blob/5c89584aacdd9e88b7d5ee60402df38e6ff9b4a4/allauth/account/adapter.py#L177-L184).
